apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spi-oauth-redirect-proxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spi-oauth-redirect-proxy
    app.kubernetes.io/part-of: spi-oauth-redirect-proxy-prod
  name: spi-oauth-redirect-proxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: spi-oauth-redirect-proxy
status:
  loadBalancer: {}
