apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-oauth-redirect-proxy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-qe-shared-tenant/spi-oauth-redirect-proxy-prod/spi-oauth-redirect-proxy@sha256:89491a1c44725d5c1078ca4c07ff9e4bb287d334a04b317cf42c8ee5a94f097a
        name: container-image
        resources: {}
status: {}
