apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-oauth-redirect-proxy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-qe-shared-tenant/spi-oauth-redirect-proxy-prod/spi-oauth-redirect-proxy@sha256:dca3fea30c81836c6f4dddd0cccf41b6c08563086633183a17ec35cdbc996426
        name: container-image
        resources: {}
status: {}
