apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-oauth-redirect-proxy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-qe-shared-tenant/spi-oauth-redirect-proxy-prod/spi-oauth-redirect-proxy@sha256:005721fbfaee61cbe296320ff79a9614aac8d40ba0fe4e2d22e01249fb3466c1
        name: container-image
        resources: {}
status: {}
