apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spi-oauth-redirect-proxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spi-oauth-redirect-proxy
    app.kubernetes.io/part-of: spi-oauth-redirect-proxy-prod
  name: spi-oauth-redirect-proxynbov
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spi-oauth-redirect-proxy
    weight: 100
status: {}
